name: Build and deploy github pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docusaurus-plus

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
          # cache-dependency-path: pnpm-lock.yaml

      - name: Cache .docusaurus directory
        uses: actions/cache@v3
        with:
          path: ./docusaurus-plus/.docusaurus
          key: docusaurus-${{ runner.os }}-${{ hashFiles('docusaurus-plus/docusaurus.config.js', 'docusaurus-plus/sidebars.js') }}
          restore-keys: |
            docusaurus-${{ runner.os }}-${{ hashFiles('docusaurus-plus/docusaurus.config.js', 'docusaurus-plus/sidebars.js') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  # https://github.com/actions/deploy-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
